'use server'

/**
 * 260707-lyq (P4 Wave 1) — journal-first attempt outcome for the capture client.
 *
 * Production evidence (attempt 8a0c13e8, 2026-07-07 19:45 UTC): a vague-input
 * attempt produced a transient $0 estimate that auto-refine later DELETED; the
 * client's DB-truth poller (lib/estimate/poll-outcome.ts) had already read the
 * doomed estimate id and navigated to a ghost. The journal (pipeline_events) is
 * the ONLY source that can tell "succeeded, and durably so" apart from
 * "succeeded, then vanished" — this action is that read-side.
 *
 * Rules (validated against production data 2026-07-07 — see PLAN <interfaces>):
 *   - completed: a generate_estimate/succeeded event exists AND its estimate_id
 *     row still exists in estimates (is_current=true).
 *   - needs_details: generate_estimate/succeeded event exists AND its
 *     estimate_id is null OR the row no longer exists.
 *   - failed: any event with status='failed' AND error_code NOT IN
 *     ('client_reported') — includes watchdog_timeout.
 *   - pending: otherwise — lastStep/lastStatus carried for stage progression.
 * Precedence: completed/needs_details are evaluated BEFORE failed — a genuine
 * terminal success wins over a stale failed row (e.g. the 18:40 false
 * client-report on attempt 4a26ffb7, which later succeeded for real).
 *
 * Never throws (matches recordPipelineEvent's D-06 best-effort discipline): a
 * read failure degrades to 'pending' so the client's own fallback + timeout
 * keeps working instead of the UI breaking on an observability hiccup.
 */
import { createClient } from '@/lib/supabase/server'
import { requireServiceClient } from '@/lib/supabase/service'
import { getActiveCompanyId } from '@/lib/queries/active-company'
import { FALLBACK_MEDIANS_MS, type StepTiming } from '@/lib/estimate/progress-model'
import {
  GENERATE_PHASE_INDEX,
  buildPhaseVisits,
  type GeneratePhase,
  type GeneratePhaseProgress,
  type GeneratePhaseVisit,
} from '@/lib/estimate/generation-phases'
import { computeJournalMedians, type MedianJournalRow } from '@/lib/estimate/journal-medians'

export type AttemptOutcome =
  | { state: 'completed'; estimateId: string }
  // QUICK-psh-02: reason/questions are additive enrichment read from
  // projects.needs_details (set once at the final vague terminal — see
  // lib/estimate/adapters/default.ts). Optional/absent when the attempt_id
  // doesn't match (stale row from a prior attempt) or the column read fails —
  // the bare `needs_details` shape stays a valid, backward-compatible outcome.
  | { state: 'needs_details'; reason?: string; questions?: string[] }
  | { state: 'failed'; step: string; reason: string }
  // 260707-o7a: pending carries the journal-derived progress payload so the
  // client can drive the REAL progress bar (lib/estimate/progress-model.ts):
  //   completedSteps — steps with a `succeeded` event, in journal order;
  //   activeStepStartedAt — created_at of the latest `started` event whose
  //   step has no `succeeded` event yet (null when nothing is mid-flight).
  // Phase 168 (PHOTO-02 UI half): analyzedCount/totalCount/failedCount are the
  // additive coverage counts 168-01 recorded on the analyze/succeeded journal
  // row's metadata (analyze-photos.ts) — optional/absent for non-photo capture
  // modes or when the analyze step hasn't reached its succeeded event yet.
  | {
      state: 'pending'
      lastStep: string | null
      lastStatus: string | null
      completedSteps: string[]
      activeStepStartedAt: string | null
      analyzedCount?: number
      totalCount?: number
      failedCount?: number
      /**
       * 260806: sub-phase narration for the `generate_estimate` step, the
       * step that owns ~90% of a capture's wall clock and used to be one
       * static label. Reconstructed from the `metadata.phase` rows the
       * pipeline writes (lib/observability/generation-phase.ts). Absent until
       * the first phase row lands, and for attempts generated by a server
       * build that predates the phase reports.
       */
      generatePhase?: GeneratePhaseProgress
      /**
       * 260927: per-step first-started / first-succeeded timestamps, so the
       * checklist can show how long each finished step took.
       */
      stepTimings?: StepTiming[]
      /**
       * 260927: every generate sub-phase visit in journal order, with its
       * merged detail. The checklist keeps finished phases on screen with the
       * facts they reported, which a single "current phase" cannot do.
       */
      phaseVisits?: GeneratePhaseVisit[]
      /**
       * 260927: created_at of the newest journal row. The client's poll uses it
       * as a heartbeat: while the server keeps writing, a long run is alive.
       */
      lastEventAt?: string | null
    }
  | { state: 'unauthorized' }

const EMPTY_PENDING = {
  state: 'pending' as const,
  lastStep: null,
  lastStatus: null,
  completedSteps: [] as string[],
  activeStepStartedAt: null,
  stepTimings: [] as StepTiming[],
  phaseVisits: [] as GeneratePhaseVisit[],
  lastEventAt: null,
}

interface JournalRow {
  step: string
  status: string
  error_code: string | null
  error_message: string | null
  estimate_id: string | null
  company_id: string | null
  // QUICK-psh-02: needed to read the project's needs_details enrichment.
  project_id: string | null
  created_at: string
  // Phase 168 (PHOTO-02 UI half): carries { analyzedCount, totalCount,
  // failedCount } on the analyze/succeeded row (analyze-photos.ts:346-360).
  // Untyped at the DB boundary — narrowed defensively where read.
  metadata: Record<string, unknown> | null
}

/**
 * QUICK-psh-02: reads projects.needs_details (set once at the final vague
 * terminal — lib/estimate/adapters/default.ts) and enriches the bare
 * needs_details outcome when it belongs to THIS attempt. Tolerates absent
 * column data, a missing projectId, or any read failure — always degrades to
 * the bare `{ state: 'needs_details' }` shape rather than throwing.
 */
async function enrichNeedsDetails(
  svc: ReturnType<typeof requireServiceClient>,
  projectId: string | null,
  attemptId: string
): Promise<AttemptOutcome> {
  if (!projectId) return { state: 'needs_details' }
  try {
    const { data } = await svc
      .from('projects')
      .select('needs_details')
      .eq('id', projectId)
      .maybeSingle()
    const nd = (
      data as { needs_details?: { reason?: string; questions?: string[]; attempt_id?: string } | null } | null
    )?.needs_details
    // Only surface the enrichment when it was written FOR this exact attempt —
    // a stale needs_details from a prior discarded attempt on the same project
    // must never bleed into a newer one's outcome.
    if (nd && nd.attempt_id === attemptId) {
      return { state: 'needs_details', reason: nd.reason, questions: nd.questions }
    }
    return { state: 'needs_details' }
  } catch (err) {
    console.warn('[getAttemptOutcome] needs-details enrichment swallowed failure:', err)
    return { state: 'needs_details' }
  }
}

export async function getAttemptOutcome(attemptId: string): Promise<AttemptOutcome> {
  try {
    // Minimal auth duplication (mirrors lib/actions/recording.ts getAuthContext) —
    // this is a read-only action, so it skips assertWritable() (no demo-mode
    // write gate applies to reading the journal).
    const supabase = await createClient()
    const { data: claimsData } = await supabase.auth.getClaims()
    const claims = claimsData?.claims ?? null
    if (!claims) return { state: 'unauthorized' }

    const activeCompanyId = await getActiveCompanyId()
    if (!activeCompanyId) return { state: 'unauthorized' }

    const svc = requireServiceClient()
    const { data } = await svc
      .from('pipeline_events')
      .select(
        'step,status,error_code,error_message,estimate_id,company_id,project_id,created_at,metadata'
      )
      .eq('attempt_id', attemptId)
      .order('created_at', { ascending: true })

    const rows = (data ?? []) as JournalRow[]
    if (rows.length === 0) {
      return { ...EMPTY_PENDING }
    }

    // Company scope: at least one row must match the caller's active company
    // (rows with a null company_id — e.g. a pre-auth early return — are
    // tolerated and never block a match on their own). No match → this
    // attempt belongs to a different tenant; never leak its outcome.
    const matchesCompany = rows.some((r) => r.company_id === activeCompanyId)
    if (!matchesCompany) return { state: 'unauthorized' }

    // Precedence: completed/needs_details (terminal success shapes) BEFORE
    // failed — see module doc.
    const succeeded = rows.find(
      (r) => r.step === 'generate_estimate' && r.status === 'succeeded'
    )
    if (succeeded) {
      if (succeeded.estimate_id) {
        const { data: estimateRow } = await svc
          .from('estimates')
          .select('id')
          .eq('id', succeeded.estimate_id)
          .eq('is_current', true)
          .maybeSingle()
        if (estimateRow) {
          return { state: 'completed', estimateId: succeeded.estimate_id }
        }
      }
      // estimate_id was null, OR the row is gone (deleted by auto-refine, the
      // 8a0c13e8 race) — the attempt did not durably produce a usable estimate.
      // QUICK-psh-02: enrich with the classification + questions persisted at
      // the vague terminal, when available for THIS attempt.
      return await enrichNeedsDetails(svc, succeeded.project_id, attemptId)
    }

    const failed = rows.find(
      (r) => r.status === 'failed' && r.error_code !== 'client_reported'
    )
    if (failed) {
      return {
        state: 'failed',
        step: failed.step,
        reason: failed.error_message ?? 'Unknown error',
      }
    }

    const last = rows[rows.length - 1]

    // 260707-o7a: progress payload for the real progress bar.
    // completedSteps: first `succeeded` occurrence per step, journal order.
    const completedSteps: string[] = []
    const succeededSteps = new Set<string>()
    for (const r of rows) {
      if (r.status === 'succeeded' && !succeededSteps.has(r.step)) {
        succeededSteps.add(r.step)
        completedSteps.push(r.step)
      }
    }
    // activeStepStartedAt: created_at of the FIRST `started` row of the step
    // that is still in flight (no `succeeded` row for it in this attempt).
    //
    // 260806: this used to take the LATEST such row, which made the overlay's
    // elapsed counter jump backwards: Inngest replays the handler at every step
    // boundary (~2.84 `started` rows per generate run in production), and the
    // sub-phase reports now add several more by design. First-row semantics
    // give the step's TRUE elapsed wall clock; the per-phase clock is carried
    // separately below.
    let activeStep: string | null = null
    for (const r of rows) {
      if (r.status === 'started' && !succeededSteps.has(r.step)) {
        activeStep = r.step
      }
    }
    const activeStepStartedAt = activeStep
      ? (rows.find((r) => r.step === activeStep && r.status === 'started')?.created_at ?? null)
      : null

    // 260806: reconstruct the generate_estimate sub-phase narration.
    // 260927: from the ordered visit list (lib/estimate/generation-phases.ts),
    // which the checklist consumes whole. generatePhase is the legacy summary
    // of it:
    //   phase:         the LAST phase reported, i.e. what is happening now.
    //   furthestPhase: the furthest phase reached, by declared order.
    //   startedAt:     created_at of the latest row for the CURRENT phase.
    const phaseVisits = activeStep === 'generate_estimate' ? buildPhaseVisits(rows) : []
    let generatePhase: GeneratePhaseProgress | undefined
    if (phaseVisits.length > 0) {
      const latest = phaseVisits[phaseVisits.length - 1]
      let furthest: GeneratePhase = latest.phase
      for (const v of phaseVisits) {
        if (GENERATE_PHASE_INDEX[v.phase] > GENERATE_PHASE_INDEX[furthest]) furthest = v.phase
      }
      const latestRow = [...rows]
        .reverse()
        .find(
          (r) =>
            r.step === 'generate_estimate' &&
            r.status === 'started' &&
            (r.metadata as { phase?: unknown } | null)?.phase === latest.phase
        )
      generatePhase = {
        phase: latest.phase,
        furthestPhase: furthest,
        startedAt: latestRow?.created_at ?? latest.startedAt,
        detail: latest.detail,
      }
    }

    // 260927: first started / first succeeded per step, journal order.
    const timingByStep = new Map<string, StepTiming>()
    for (const r of rows) {
      let t = timingByStep.get(r.step)
      if (!t) {
        t = { step: r.step, startedAt: null, finishedAt: null }
        timingByStep.set(r.step, t)
      }
      if (r.status === 'started' && !t.startedAt) t.startedAt = r.created_at ?? null
      if (r.status === 'succeeded' && !t.finishedAt) t.finishedAt = r.created_at ?? null
    }
    const stepTimings = [...timingByStep.values()]

    // Phase 168 (PHOTO-02 UI half): surface the analyze step's coverage
    // counts (168-01's analyze-photos.ts metadata) so the client can render
    // "N of M photos analyzed" while generation is still pending. Absent for
    // non-photo capture modes or before the analyze/succeeded row lands.
    const analyzeRow = rows.find((r) => r.step === 'analyze' && r.status === 'succeeded')
    const analyzeMetadata = analyzeRow?.metadata as
      | { analyzedCount?: unknown; totalCount?: unknown; failedCount?: unknown }
      | null
      | undefined
    const analyzedCount =
      typeof analyzeMetadata?.analyzedCount === 'number' ? analyzeMetadata.analyzedCount : undefined
    const totalCount =
      typeof analyzeMetadata?.totalCount === 'number' ? analyzeMetadata.totalCount : undefined
    const failedCount =
      typeof analyzeMetadata?.failedCount === 'number' ? analyzeMetadata.failedCount : undefined

    return {
      state: 'pending',
      lastStep: last.step,
      lastStatus: last.status,
      completedSteps,
      activeStepStartedAt,
      ...(analyzedCount !== undefined ? { analyzedCount } : {}),
      ...(totalCount !== undefined ? { totalCount } : {}),
      ...(failedCount !== undefined ? { failedCount } : {}),
      ...(generatePhase ? { generatePhase } : {}),
      stepTimings,
      phaseVisits,
      lastEventAt: last.created_at ?? null,
    }
  } catch (err) {
    // Never throw — a read failure must not break the client's polling loop.
    console.warn('[getAttemptOutcome] swallowed read failure:', err)
    return { ...EMPTY_PENDING }
  }
}

/**
 * Live typical durations for the capture checklist (lib/estimate/progress-model.ts).
 *
 * 260927: measured as gaps between journal timestamps of the same attempt
 * (computeJournalMedians): per step, and per generate sub-phase under
 * `generate_estimate:<phase>` keys. The sub-phase keys are what let the
 * checklist weight "Writing the scope of work" as the long stretch it really
 * is instead of a fixed guess. Merged over {@link FALLBACK_MEDIANS_MS}; any key
 * with too few samples is left to the model's own fallbacks.
 *
 * Company-AGNOSTIC aggregate (timestamps and phase names only, no tenant data
 * leaves this function). Auth-gated like getAttemptOutcome. On ANY failure it
 * degrades to the static fallbacks: the checklist must never break on an
 * observability read hiccup.
 *
 * Bounded window: the most recent 6000 started/succeeded rows of the last 30
 * days (~150 attempts now that drafting reports add rows), read in created_at
 * order off the existing index, with only the phase name pulled from metadata.
 *
 * Call ONCE per capture session (the client caches it), NOT per poll tick.
 */
export async function getStepMedians(): Promise<Record<string, number>> {
  try {
    const supabase = await createClient()
    const { data: claimsData } = await supabase.auth.getClaims()
    const claims = claimsData?.claims ?? null
    if (!claims) return { ...FALLBACK_MEDIANS_MS }

    const activeCompanyId = await getActiveCompanyId()
    if (!activeCompanyId) return { ...FALLBACK_MEDIANS_MS }

    const svc = requireServiceClient()
    const since = new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString()
    const { data, error } = await svc
      .from('pipeline_events')
      // Only the phase name out of `metadata`: the live drafting reports carry
      // section titles, and 6000 of those would be megabytes for nothing.
      .select('attempt_id,step,status,created_at,phase:metadata->>phase')
      .in('status', ['started', 'succeeded'])
      .gte('created_at', since)
      .order('created_at', { ascending: false })
      .limit(6000)
    if (error) return { ...FALLBACK_MEDIANS_MS }

    const rows: MedianJournalRow[] = ((data ?? []) as unknown as Array<{
      attempt_id: string | null
      step: string
      status: string
      created_at: string
      phase: string | null
    }>).map((r) => ({
      attempt_id: r.attempt_id,
      step: r.step,
      status: r.status,
      created_at: r.created_at,
      metadata: r.phase ? { phase: r.phase } : null,
    }))

    return { ...FALLBACK_MEDIANS_MS, ...computeJournalMedians(rows) }
  } catch (err) {
    console.warn('[getStepMedians] swallowed read failure:', err)
    return { ...FALLBACK_MEDIANS_MS }
  }
}
